# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: Build dotnet in dev container

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
    - 'src/**'
    - '.devcontainer/**'
  pull_request:
    branches: [ "main" ]
    paths:
    - 'src/**'
    - '.devcontainer/**'

jobs: 
  build:
    defaults:
      run:
        shell: bash

    runs-on: ubuntu-latest

    env:
      SOURCE_PATH: ./src

    steps:

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/checkout@v3

    - name: Run .NET format/build/test
      uses: devcontainers/ci@v0.3
      with:
        imageName: ghcr.io/${{ github.repository_owner }}/dotnet-devcontainer
        env: |
          SOURCE_PATH
        runCmd: bash ./scripts/build-dotnet.sh

    - name: Copy coverage.cobertura.xml
      run: cp $SOURCE_PATH/coverage/*/coverage.cobertura.xml $SOURCE_PATH/coverage/coverage.cobertura.xml    

    - name: Generate Coverage Report as Markdown
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: ${{ env.SOURCE_PATH }}/coverage/coverage.cobertura.xml
        badge: true
        format: 'markdown'
        output: 'both'

    - name: Add Coverage Report to PR
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md

    - name: Add Coverage Report to Job Summary
      run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
